name: dicee
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  # Set your app icon path here
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
#  ios: true
#  image_path: "assets/icon/go_cute.png"
flutter:
  uses-material-design: true
  assets:
    - images/dice1.png
    - images/dice2.png
    - images/dice3.png
    - images/dice4.png
    - images/dice5.png
    - images/dice6.png
  fonts:
    - family: Honk
      fonts:
        - asset: fonts/Honk-Regular.ttf
    - family: Kablammo
      fonts:
        - asset: fonts/Kablammo-Regular.ttf






